### ISSUE TITLE
Full-text search needed

### ISSUE THREAD

**Issue by esokullu** [pho-adapters/index-mysql#1]
Right now when I make the attribute "Emre Sokullu" and search for "Emre", it does not return any value. Indexing should be full text by default.

**Comment by poratuk** [comment]
Done by [this commit](https://github.com/pho-adapters/index-mysql/commit/f23af70cb927e8b475eaaab60e03d843c4201651)

**Comment by esokullu** [comment]
commented on the commit. but this should be ok.
