### ISSUE TITLE
File/class naming

### ISSUE THREAD

**Issue by esokullu** [pho-adapters/index-mysql#4]
Not MySQL.php but it should be Mysql.php and class Mysql

**Comment by poratuk** [comment]
Done by [commit 1](https://github.com/pho-adapters/index-mysql/commit/baf471436ef7e068bde8e2411d61cae46cc65d81) and [commit2](https://github.com/pho-adapters/index-mysql/commit/4d12728a8a58a5f42a4e69d0c291f113d107bd21)
